# Generated by Django 2.1.7 on 2019-08-03 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190731_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='experience',
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
