# Generated by Django 2.1.7 on 2019-08-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190806_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
