# Generated by Django 2.1.7 on 2019-08-20 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190806_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_players', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_groups', to='core.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamGroupPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_group_players', to='core.TeamGroup')),
                ('team_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_group_players', to='core.TeamPlayer')),
            ],
        ),
        migrations.AddField(
            model_name='teamgroup',
            name='team_players',
            field=models.ManyToManyField(through='core.TeamGroupPlayer', to='core.TeamPlayer'),
        ),
    ]
