# Generated by Django 2.1.7 on 2019-08-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190821_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgroup',
            name='calculated_ponderation',
            field=models.FloatField(null=True),
        ),
    ]
