# Generated by Django 2.1.7 on 2019-09-01 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teamgroup_calculated_ponderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80, unique=True)),
                ('rule_type', models.CharField(choices=[('presence', 'Presence'), ('goal', 'Goal'), ('goal_conceded', 'Goal Conceded'), ('clean_sheet', 'Clean Sheet'), ('own_goal', 'Own Goal')], max_length=50)),
                ('default_points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='TeamRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rules', to='core.Rule')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rules', to='core.Team')),
            ],
        ),
    ]
