# Generated by Django 2.1.7 on 2019-09-01 17:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rule_teamrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('team_group_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.TeamGroupPlayer')),
            ],
        ),
        migrations.RenameField(
            model_name='teamrule',
            old_name='points',
            new_name='points_amount',
        ),
        migrations.AddField(
            model_name='point',
            name='team_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.TeamRule'),
        ),
    ]
