# Generated by Django 2.1.7 on 2019-09-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190901_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='default_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('presence', 'Presence'), ('goal', 'Goal'), ('hattrick', 'Hattrick'), ('goal_conceded', 'Goal Conceded'), ('clean_sheet', 'Clean Sheet'), ('own_goal', 'Own Goal'), ('game_victory', 'Game Victory'), ('game_defeat', 'Game Defeat')], max_length=50, unique=True),
        ),
    ]
