# Generated by Django 2.1.7 on 2019-09-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190902_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='points',
            new_name='points_amount',
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('presence', 'Presence'), ('goal', 'Goal'), ('hattrick', 'Hattrick'), ('goals_conceded', 'Goals Conceded'), ('goals_scored', 'Goal Scored'), ('clean_sheet', 'Clean Sheet'), ('own_goal', 'Own Goal'), ('game_victory', 'Game Victory'), ('game_defeat', 'Game Defeat'), ('game_mvp', 'Game MVP')], max_length=50, unique=True),
        ),
    ]
