# Generated by Django 2.1.7 on 2019-09-03 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190903_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgroupplayer',
            name='points_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
