# Generated by Django 2.1.7 on 2019-09-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_teamgroupplayer_points_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner_team',
        ),
        migrations.AlterField(
            model_name='goal',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_goals', to='core.TeamGroupPlayer'),
        ),
    ]
