# Generated by Django 2.1.7 on 2019-09-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190904_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_away_team', to='core.TeamGroup'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_home_team', to='core.TeamGroup'),
        ),
    ]
