# Generated by Django 2.1.7 on 2019-09-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190904_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgroup',
            name='game',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='team_groups', to='core.Game'),
            preserve_default=False,
        ),
    ]
