# Generated by Django 2.1.7 on 2019-09-09 19:31

import django.core.validators
from django.db import migrations, models
import team_maker.core.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_game_finished'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', team_maker.core.models.user.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='position',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
