# Generated by Django 2.1.7 on 2019-09-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190909_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAvailablePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('unknown', 'Unknown'), ('going', 'Going'), ('not_going', 'Not Going')], default='unknown', max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_players', to='core.Game')),
                ('team_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_players', to='core.TeamPlayer')),
            ],
        ),
    ]
