# Generated by Django 2.2.5 on 2019-09-24 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_gameavailableplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgroup',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_groups', to='core.Game'),
        ),
        migrations.AlterField(
            model_name='teamgroup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_groups', to='core.Team'),
        ),
    ]
