# Generated by Django 2.2.5 on 2019-09-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190924_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgroupplayer',
            name='team_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_group_players', to='core.TeamGroup'),
        ),
        migrations.AlterField(
            model_name='teamgroupplayer',
            name='team_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_group_players', to='core.TeamPlayer'),
        ),
    ]
