# Generated by Django 2.2.5 on 2019-09-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20190924_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgroup',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_groups', to='core.Game'),
        ),
        migrations.AlterField(
            model_name='teamgroup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_groups', to='core.Team'),
        ),
        migrations.AlterField(
            model_name='teamgroupplayer',
            name='team_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_group_players', to='core.TeamGroup'),
        ),
        migrations.AlterField(
            model_name='teamgroupplayer',
            name='team_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_group_players', to='core.TeamPlayer'),
        ),
    ]
