# Generated by Django 2.2.5 on 2019-09-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190925_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='core.Team'),
        ),
    ]
